### ISSUE TITLE
启动出现问题

### ISSUE THREAD

**Issue by w1159590346** [0999312/Sakura_mod#135]
以下是崩溃报告  不知道和哪一个MOD有冲突
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2022/6/4 下午1:08
Description: Rendering overlay

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.material.FlowingFluid.m_76068_(boolean)" because the return value of "net.minecraft.world.level.block.LiquidBlock.getFluid()" is null
	at net.minecraft.world.level.block.LiquidBlock.initFluidStateCache(LiquidBlock.java:181) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A}
	at net.minecraft.world.level.block.LiquidBlock.m_5888_(LiquidBlock.java:89) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handler$zkb003$init(BlockBehaviour.java:2399) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:radon.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:radon.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:518) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.25.jar%2393!/:?] {}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:185) ~[fmlcore-1.18.2-40.1.25.jar%2393!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$finishMods$17(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.25.jar%2393!/:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:175) ~[fmlcore-1.18.2-40.1.25.jar%2393!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$finishModLoading$6(ClientModLoader.java:127) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:113) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.finishModLoading(ClientModLoader.java:127) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$3(ClientModLoader.java:106) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.block.LiquidBlock.initFluidStateCache(LiquidBlock.java:181) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A}
	at net.minecraft.world.level.block.LiquidBlock.m_5888_(LiquidBlock.java:89) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,re:classloading,pl:accesstransformer:B,xf:fml:forge:flowing_fluid_block,pl:mixin:APP:roughlyenoughresources.mixins.json:FluidBlockHooks,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.handler$zkb003$init(BlockBehaviour.java:2399) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:radon.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:radon.mixins.json:block.MixinAbstractBlockState,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:A}
	at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:518) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:591) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:297) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:572) ~[guava-31.0.1-jre.jar%2328!/:?] {}
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:295) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$5(ForgeStatesProvider.java:33) ~[forge-1.18.2-40.1.25-universal.jar%2396!/:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:rubidium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:seamless_loading_screen:Minecraft#clearLevel,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:rubidium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2392!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.25.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 6539245416 bytes (6236 MiB) / 7029653504 bytes (6704 MiB) up to 7029653504 bytes (6704 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Graphics card #1 name: LuminonCore IDDCX Adapter
	Graphics card #1 vendor: LuminonCore
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: unknown
	Graphics card #1 versionInfo: DriverVersion=1.0.2018.1204
	Graphics card #2 name: NVIDIA GeForce RTX 2060
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x1f15
	Graphics card #2 versionInfo: DriverVersion=30.0.15.1295
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.93
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.93
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30586.80
	Virtual memory used (MB): 18206.55
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 205.73
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx6698m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Loaded Shaderpack: (off)
	Launched Version: 1.18.2-幻想绯乡-Fabric
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.95, NVIDIA Corporation
	Window size: 1600x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 16x Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		00[N][优化]氡radon-0.8.1.jar                         |Radon                         |radon                         |0.8.1               |DONE      |Manifest: NOSIGNATURE
		00[N][优化]镭radium-0.7.10.jar                       |Radium                        |radium                        |0.7.10              |DONE      |Manifest: NOSIGNATURE
		[N][附魔描述]EnchantmentDescriptions-Forge-1.18.2-10.0|EnchantmentDescriptions       |enchdesc                      |10.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		01[Y][增强装备]EnhancedArmaments-forge-1.18.2-1.1.0.ja|Enhancedarmaments             |enhancedarmaments             |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		[M][自然音效]AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar |Ambient Sounds                |ambientsounds                 |5.0.16              |DONE      |Manifest: NOSIGNATURE
		[M][鼠标手势]MouseTweaks-forge-mc1.18-2.21.jar        |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		[N][菜单]ConfigMenusForge-v3.2.0-1.18.2-Forge.jar   |Config Menus for Forge        |configmenusforge              |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		[Y][前置]CreativeCore_FORGE_v2.6.9_mc1.18.2.jar     |CreativeCore                  |creativecore                  |2.6.9               |DONE      |Manifest: NOSIGNATURE
		[M][皮肤补丁]CustomSkinLoader_ForgeActive-14.14-SNAPSH|CustomSkinLoader              |customskinloader              |14.14-SNAPSHOT-323  |DONE      |Manifest: 4a:31:8b:cf:34:eb:d0:13:f3:19:39:d5:d2:b9:12:78:b5:f2:8d:91:3e:6f:8f:ed:97:48:00:69:e1:30:3a:54
		01[Y][REI]RoughlyEnoughItems-8.2.470.jar          |Roughly Enough Items (REI)    |roughlyenoughitems            |8.2.470             |DONE      |Manifest: NOSIGNATURE
		[Y][动态光源]dynamiclights-1.18.6.jar                 |Dynamic Lights                |dynamiclights                 |1.18.6              |DONE      |Manifest: NOSIGNATURE
		01[Y][樱前置]mmlib-1.0.2-1.18.2.jar                  |Mysterious Mountain Lib       |mmlib                         |1.0.2-1.18.2        |DONE      |Manifest: NOSIGNATURE
		00[N][优化]铷rubidium-0.5.2a.jar                     |Rubidium                      |rubidium                      |0.5.2a              |DONE      |Manifest: NOSIGNATURE
		[Y][前置]Iceberg-1.18.2-1.0.44.jar                  |Iceberg                       |iceberg                       |1.0.44              |DONE      |Manifest: NOSIGNATURE
		[M][血量Neat+1.8-30.jar                             |Neat                          |neat                          |1.8-30              |DONE      |Manifest: NOSIGNATURE
		[N]地图Xaeros_Minimap_22.8.2_Forge_1.18.2.jar       |Xaero's Minimap               |xaerominimap                  |22.8.2              |DONE      |Manifest: NOSIGNATURE
		00[N][优化]铷附属oculus-mc1.18.2-1.2.4.jar             |Oculus                        |oculus                        |1.2.4               |DONE      |Manifest: NOSIGNATURE
		[M][落叶]Fallingleaves-1.18.2-1.3.2.jar             |Falling Leaves                |fallingleaves                 |1.3.2               |DONE      |Manifest: NOSIGNATURE
		[N]地图XaerosWorldMap_1.22.0_Forge_1.18.2.jar       |Xaero's World Map             |xaeroworldmap                 |1.22.0              |DONE      |Manifest: NOSIGNATURE
		01[Y][樱]sakura-1.0.1-1.18.2.jar                   |Sakura Mod                    |sakura                        |1.0.1-1.18.2        |DONE      |Manifest: NOSIGNATURE
		[M][物品边框]ItemBorders-1.18.1-1.1.5.jar             |Item Borders                  |itemborders                   |1.1.5               |DONE      |Manifest: NOSIGNATURE
		[M][无感加载界面]seamless_loading_screen-1.18-3.0.0.jar |Seamless Loading Screen       |seamless_loading_screen       |1.18-3.0.0          |DONE      |Manifest: NOSIGNATURE
		[M][背包HUD]InventoryHud_[1.18].forge-3.4.4.jar     |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.4               |DONE      |Manifest: NOSIGNATURE
		01[Y][附魔描述前置]Bookshelf-Forge-1.18.2-13.0.13.jar   |Bookshelf                     |bookshelf                     |13.0.13             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[M][食物动画]eatinganimation-1.18.1-2.0.2.jar         |Eating Animation              |eatinganimation               |2.0.0               |DONE      |Manifest: NOSIGNATURE
		01[Y][创世神]worldedit-mod-7.2.10.jar                |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		[N][一键整理]InventoryProfilesNext-forge-1.18.2-1.5.0.|Inventory Profiles Next       |inventoryprofilesnext         |1.5.0               |DONE      |Manifest: NOSIGNATURE
		[N][前置]architectury-4.4.68.jar                    |Architectury                  |architectury                  |4.4.68              |DONE      |Manifest: NOSIGNATURE
		01[N][REI附属rer-2.5.1.jar                          |Roughly Enough Resources      |roughlyenoughresources        |2.5.1               |DONE      |Manifest: NOSIGNATURE
		[M][披风]WaveyCapes-forge-1.2.0-mc1.18.jar          |WaveyCapes Mod                |waveycapes                    |1.2.0               |DONE      |Manifest: NOSIGNATURE
		[Y][拾取提示]PickUpNotifier-v3.2.0-1.18.2-Forge.jar   |Pick Up Notifier              |pickupnotifier                |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		[M][物理掉落]ItemPhysic_v1.4.23_mc1.18.2.jar          |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |Manifest: NOSIGNATURE
		[Y][前置]PuzzlesLib-v3.3.5-1.18.2-Forge.jar         |Puzzles Lib                   |puzzleslib                    |3.3.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		01[Y]服务器动态视距dynview-1.18.2-2.7.jar                |Dynamic view distance         |dynview                       |2.3                 |DONE      |Manifest: NOSIGNATURE
		[N][更好的F3]BetterF3-1.2.5-Forge-1.18.2.jar         |BetterF3                      |betterf3                      |1.2.5               |DONE      |Manifest: NOSIGNATURE
		[N][FPS节能]FpsReducer2-forge-1.18.2-2.0.jar        |FPS Reducer                   |fpsreducer                    |1.18.2-2.0          |DONE      |Manifest: NOSIGNATURE
		[Y][前置]cloth-config-6.2.62-forge.jar              |Cloth Config v4 API           |cloth_config                  |6.2.62              |DONE      |Manifest: NOSIGNATURE
		[M][立体皮肤]3dskinlayers-forge-1.4.6-mc1.18.2.jar    |3dSkinLayers                  |skinlayers3d                  |1.4.6               |DONE      |Manifest: NOSIGNATURE
		00[N][优化]铷镁附属rubidium_extras-1.18.2_v1.3.1.jar    |Rubidium Extras               |rubidium_extras               |1.18.2_v1.3.1       |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.25-universal.jar                |Forge                         |forge                         |40.1.25             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		[N][细节盔甲]DetailArmorBar-2.6.2+1.18.2-forge.jar    |Detail Armor Bar              |detailab                      |2.6.2+1.18.2-forge  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 17a16b99-495e-43d6-8d0d-a6e0db7bb10f
	FML: 40.1
	Forge: net.minecraftforge:40.1.25

**Comment by w1159590346** [comment]
找到了 冲突的mod   [RER]Roughly Enough Resources

**Comment by 0999312** [comment]
已修复
