### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by w1159590346** [0999312/Sakura_mod#136]
[13:32:21] [main/INFO]: ModLauncher running: args [--username, Ai_Yasiting, --version, 1.18.2-幻想绯乡-Fabric, --gameDir, D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft, --assetsDir, D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\assets, --assetIndex, 1.18, --uuid, 4e2d3ca8e8f73e50bfd300dffe61da7e, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, HMCL 3.5.3, --width, 1366, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.25, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[13:32:21] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.3.1 by Oracle Corporation
[13:32:21] [main/INFO]: OptiFineTransformationService.onLoad
[13:32:21] [main/INFO]: OptiFine ZIP file URL: union:/D:/游戏/A_Game/mc/幻想乡4.1.1/.minecraft/mods/00%5BN%5D%5B高清修复%5DOptiFine_1.18.2_HD_U_H7.jar%2352!/
[13:32:21] [main/INFO]: OptiFine ZIP file: D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods\00[N][高清修复]OptiFine_1.18.2_HD_U_H7.jar
[13:32:21] [main/INFO]: Target.PRE_CLASS is available
[13:32:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/游戏/A_Game/mc/幻想乡4.1.1/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[13:32:22] [main/INFO]: OptiFineTransformationService.initialize
[13:32:22] [main/INFO]: Found mod file 00[F]合作进度CooperativeAdvancements-1.18.2-1.2.3.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 00[N][优化]Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 00[N][优化]氡radon-0.8.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 00[N][优化]镭radium-0.7.10.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 00[Y][优化]krypton-0.1.10-SNAPSHOT.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[N[中文输入法]imblocker-1.18.1-3.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[N[无夜视闪烁]no_nv_flash-1.18.2-1.4.0.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[N[服务器×]MyServerIsCompatible-1.18-1.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[N[玉]Jade-1.18.2-forge-5.2.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][jeI]jei-1.18.2-9.7.0.196.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][jeI]JustEnoughCharacters-1.18.1-4.3.3.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][jeI扩展]jeiintegration_1.18.2-9.0.0.37.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][伊卡洛斯]locusazzurro_icaruswings-1.18.2-0.4.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][创世神]worldedit-mod-7.2.10.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][增强装备]EnhancedArmaments-forge-1.18.2-1.1.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][实验假人]MmmMmmMmmMmm-1.18.2-1.5.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][帕秋莉手册]Patchouli-1.18.2-69.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][旅行者背包]TravelersBackpack-1.18.2-7.1.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][更多箱子]ironchest-1.18.2-13.1.9.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][祛魔台]DisenchantmentEditTable-1.18.1-1.0.7.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][管道]refinedpipes-0.6.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][精英怪物]infernalmobs-1.18.5.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][车万女仆]touhoulittlemaid-1.18.2-1.0.0-alpha.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][附魔描述前置]Bookshelf-Forge-1.18.2-13.0.13.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 01[Y][饰品栏]curios-forge-1.18.2-5.0.7.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][凿子工艺]ChiselsBits-forge-1.18.2-1.2.90-universal.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][家具]cfm-7.0.0-pre29-1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][更多窗户]mcw-windows-2.0.3-mc1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][更多门]mcw-doors-1.0.6-mc1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][樱前置]mmlib-1.0.2-1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][灯具扩展]extlights-4.4.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 02[Y][装饰方块]Decorative+Blocks-forge-1.18.2-2.1.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 03[Y][农夫乐事]FarmersDelight-1.18.2-1.1.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 04[Y][吸血鬼传说]Vampirism-1.18.2-1.8.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 04[Y][吸血鬼传说前置]Guide-API-VP-1.18.1-2.2.3.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 04[Y][吸血鬼传说狼人]Werewolves-1.18.2-1.8-0.6.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 04[Y][起源职业]origins-classes-forge-1.1.5.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 04[Y][起源职业前置]Origins-1.18.2-1.4.1.1-unified.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 04[Y][起源职业前置前置]caelus-forge-1.18.1-3.0.0.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 05[Y][AE2]appliedenergistics2-11.1.3 .jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 05[Y][AE2附属]AE2WTLib-11.1.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 05[Y][通用机械]Mekanism-1.18.2-10.2.2.462.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 05[Y][通用机械附属]MekanismGenerators-1.18.2-10.2.2.462.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 06[Y][神秘遗物]EnigmaticLegacy-2.23.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file 09[YYDS][通量网络]FluxNetworks-1.18.2-7.0.2.3.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][披风]WaveyCapes-forge-1.2.0-mc1.18.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][无感加载界面]seamless_loading_screen-1.18-3.0.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][汉化]i18nupdatemod-1.18-3.0.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][物品边框]ItemBorders-1.18.1-1.1.5.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][物理掉落]ItemPhysic_v1.4.23_mc1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][皮肤补丁]CustomSkinLoader_ForgeActive-14.14-SNAPSHOT-323.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][立体皮肤]3dskinlayers-forge-1.4.6-mc1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][纹理链接]CTM-1.18.2-1.1.4+4.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][背包HUD]InventoryHud_[1.18].forge-3.4.4.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][自然音效]AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][血量Neat+1.8-30.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][食物动画]eatinganimation-1.18.1-2.0.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [M][鼠标手势]MouseTweaks-forge-mc1.18-2.21.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][FPS节能]FpsReducer2-forge-1.18.2-2.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][一键整理]InventoryProfilesNext-forge-1.18.2-1.5.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][更好的F3]BetterF3-1.2.5-Forge-1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][服务器延迟查看]BetterPingDisplay-1.18.2-1.1.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][细节盔甲]DetailArmorBar-2.6.2+1.18.2-forge.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][菜单]ConfigMenusForge-v3.2.0-1.18.2-Forge.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N][附魔描述]EnchantmentDescriptions-Forge-1.18.2-10.0.3.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N]地图Xaeros_Minimap_22.9.3_Forge_1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [N]地图XaerosWorldMap_1.23.3_Forge_1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [Y][前置]architectury-4.5.75-forge.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [Y][前置]cloth-config-6.2.62-forge.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [Y][前置]CreativeCore_FORGE_v2.6.9_mc1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [Y][前置]Iceberg-1.18.2-1.0.44.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [Y][前置]PuzzlesLib-v3.3.5-1.18.2-Forge.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file [Y][苹果皮]appleskin-forge-mc1.18-2.4.0.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file sakura-1.0.2-1.18.2.jar of type MOD with locator {mods folder locator at D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\mods}
[13:32:22] [main/INFO]: Found mod file fmlcore-1.18.2-40.1.25.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@625e134e
[13:32:22] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.1.25.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@625e134e
[13:32:22] [main/INFO]: Found mod file mclanguage-1.18.2-40.1.25.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@625e134e
[13:32:22] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@625e134e
[13:32:22] [main/INFO]: Found mod file forge-1.18.2-40.1.25-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@625e134e
[13:32:22] [main/ERROR]: Missing mandatory dependencies: mmlib
[13:32:22] [main/INFO]: OptiFineTransformationService.transformers
[13:32:22] [main/INFO]: Targets: 350
[13:32:23] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[13:32:24] [main/INFO]: Compatibility level set to JAVA_17
[13:32:24] [main/ERROR]: Mixin config radon.mixins.json does not specify "minVersion" property
[13:32:24] [main/ERROR]: Mixin config radium.mixins.json does not specify "minVersion" property
[13:32:24] [main/INFO]: Successfully loaded Mixin Connector [com.integral.enigmaticlegacy.MixinConnector]
[13:32:24] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.18.2-幻想绯乡-Fabric, --gameDir, D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft, --assetsDir, D:\游戏\A_Game\mc\幻想乡4.1.1\.minecraft\assets, --uuid, 4e2d3ca8e8f73e50bfd300dffe61da7e, --username, Ai_Yasiting, --assetIndex, 1.18, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, HMCL 3.5.3, --width, 1366, --height, 768]
[13:32:24] [main/INFO]: Loaded configuration file for Radium: 100 options available, 0 override(s) found
[13:32:25] [main/WARN]: Error loading class: shadows/apotheosis/ench/table/ApothEnchantContainer (java.lang.ClassNotFoundException: shadows.apotheosis.ench.table.ApothEnchantContainer)
[13:32:25] [main/WARN]: Error loading class: net/darkhax/darkutils/features/charms/CharmEffects (java.lang.ClassNotFoundException: net.darkhax.darkutils.features.charms.CharmEffects)
[13:32:25] [main/WARN]: Error loading class: com/brandon3055/csg/ModEventHandler (java.lang.ClassNotFoundException: com.brandon3055.csg.ModEventHandler)
[13:32:25] [main/WARN]: Error loading class: vazkii/quark/content/client/module/ImprovedTooltipsModule (java.lang.ClassNotFoundException: vazkii.quark.content.client.module.ImprovedTooltipsModule)
[13:32:25] [main/WARN]: Error loading class: vazkii/quark/content/tweaks/module/AutomaticRecipeUnlockModule (java.lang.ClassNotFoundException: vazkii.quark.content.tweaks.module.AutomaticRecipeUnlockModule)
[13:32:25] [main/WARN]: Error loading class: vazkii/quark/content/client/tooltip/AttributeTooltips (java.lang.ClassNotFoundException: vazkii.quark.content.client.tooltip.AttributeTooltips)
[13:32:25] [main/WARN]: Error loading class: vazkii/quark/content/management/client/screen/widgets/MiniInventoryButton (java.lang.ClassNotFoundException: vazkii.quark.content.management.client.screen.widgets.MiniInventoryButton)
[13:32:26] [main/INFO]: Mixing MixinPlayer from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.entity.player.Player
[13:32:26] [main/INFO]: Mixing MixinLivingEntity from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.entity.LivingEntity
[13:32:26] [main/INFO]: Mixing MixinItemStack from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.item.ItemStack
[13:32:27] [main/INFO]: Mixing MixinEntityRenderer from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.client.renderer.entity.EntityRenderer
[13:32:27] [main/INFO]: Mixing MixinMobEffect from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.effect.MobEffect
[13:32:27] [main/WARN]: Method overwrite conflict for getHiddenEffect in apoli.mixins.json:StatusEffectInstanceMixin, previously written by de.teamlapen.vampirism.mixin.MixinEffectInstance. Skipping method.
[13:32:27] [main/WARN]: Method overwrite conflict for getHiddenEffect in werewolves.mixins.json:MobEffectInstanceAccessor, previously written by de.teamlapen.vampirism.mixin.MixinEffectInstance. Skipping method.
[13:32:27] [main/INFO]: Mixing AccessorAbstractArrowEntity from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.world.entity.projectile.AbstractArrow
[13:32:27] [main/INFO]: Mixing MixinItemRenderer from assets/enigmaticlegacy/enigmaticlegacy.mixins.json into net.minecraft.client.renderer.entity.ItemRenderer
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.25/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @1e9469b8; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @1e9469b8)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.25/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138)
	... 13 more
Caused by: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @1e9469b8; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @1e9469b8)
	at TRANSFORMER/radium@0.7.10/me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_166049_(Shapes.java:1601)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83048_(Shapes.java:50)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.<clinit>(Shapes.java:26)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Block.m_49796_(Block.java:138)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.SaplingBlock.<clinit>(SaplingBlock.java:20)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:59)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
	at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	启动器开始后就直接崩溃

**Comment by w1159590346** [comment]
1.0.1是没有问题的 1.0.2就崩溃

**Comment by 0999312** [comment]
你应该想想你该不该装高清修复。

**Comment by w1159590346** [comment]
我也不想用高清修复，但是Oculus和飞轮有严重冲突，我没选择

**Comment by w1159590346** [comment]
> 以及建议更新到MMLib到1.0.3
解决了 MMLib更新到最新的就好了 
我也不想用高清修复，Oculus和飞轮有严重的冲突，我没选择

**Comment by w1159590346** [comment]
> 以及建议更新到MMLib到1.0.3

谢谢！
